### ISSUE TITLE
Is this project still alive or is it dead?

### ISSUE THREAD

**Issue by COLABORATI** [hardening-io/hardening#7]
Hi, I am especially interested in progress on the ansible modules. What is the status of this project?
Thanks for your attention!

**Comment by rndmh3ro** [comment]
This prject is certainly not dead! Just 10 days ago we released the ansible hardening roles in version 3.0, officially supporting Ansible 2.0.

**Comment by chris-rock** [comment]
@COLABORATI I am not sure, why you think this should be dead. Could you share the reasons?

Its very active and we adapt the implementation and tests. At the moment we redevelop all our testing and make it more easy to maintain our testing framework. This makes it easier to ensure the quality of the project.

In additional, I like to mention, that the project is fully independently of any corporation. I encourage you to contribute the additions you need.

**Comment by COLABORATI** [comment]
Yes, i can share my reasons, it looked a little death because the last commit was 11 months ago, what made me believe that the project is sleeping. Also I see that relatively simple tasks are taking a very long time, so that project looked like authors moved on with other things. 

Would you like to please explain what do you mean by "independent by any company"? I see german telecom all over the place, very prominently placed on your website, so of course the expectations for a project made by german telecom are a little bit higher than for any random project made by a random joe in his sleeping room. So is it a telekom project or not? 

However in your chat i learned that you are transitioning to the new chef infrastructure and that you are working on it. However, from just looking at this repo the project looked a bit sleeping.
